#
# Vivado (TM) v2016.2 (64-bit)
#
# create_yarr_RD53A_kc705_project.tcl: Tcl script for re-creating project 'yarr'
#
# Generated by Vivado on Thu Jul 26 17:54:49 JST 2018
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_yarr_RD53A_kc705_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/constrs_kc705_timing.xdc"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/constrs_kc705_ddr3.xdc"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/constrs_kc705.xdc"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/constrs_kc705_ila.xdc"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/constrs_kc705_dual_ohio.xdc"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_pkg.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_disp.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut_base.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_bram.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_rtl.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/xapp1017/delay_controller_wrap.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/cdr_serdes.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/xapp1017/serdes_1_to_468_idelay_ddr.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_top.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/gn4124_core_pkg.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/gearbox32to66.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/descrambler.v"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/aurora_rx_lane.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/data_alignment.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/tx-core/serial_port.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller_wb_slave.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/rr_arbiter.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core_pkg.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/bram_rd53a_octa_ohio/board_pkg.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/l2p_fifo.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/synchronizer.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_wrapper.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/common_pkg.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/generic_async_fifo_wrapper.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/tx-core/tx_channel.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/tx-core/trigger_unit.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/p2l_dma_master.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/aurora_rx_channel.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_read_core.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/i2c-master/i2c_master_bit_ctrl.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/dma_controller.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/trigger-logic/delayer.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_write_core.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/fei4_rx_channel.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/i2c-master/i2c_master_byte_ctrl.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/i2c-master/i2c_master_registers.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/wbmaster32.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/trigger-logic/eudet_tlu.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/l2p_dma_master.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/l2p_arbiter.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/p2l_decoder.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/trigger-logic/edge_detector.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/simple_counter.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/wb_spi.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/wb_addr_decoder.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/trigger-logic/wb_trigger_logic.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/wbexp-core/wbexp_core.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/i2c-master/i2c_master_wb_top.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/xpressk7/app_pkg.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/ddr3k7-core/ddr3_ctrl_wb.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/wb_rx_core.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/common/k_dual_bram.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/tx-core/wb_tx_core.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/rtl/kintex7/rx-core/wb_rx_bridge.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/xpressk7/app.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/syn/kc705/bram_yarr_kc705_dual_ohio.vhd"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_b.prj"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/clk_gen/clk_gen.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_29x32/fifo_29x32.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_32x512/fifo_32x512.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_64x512/fifo_64x512.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_8x32/fifo_8x32.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/fifo_96x512_1/fifo_96x512.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/ila_axis/ila_axis.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/ila_ddr/ila_ddr.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/ila_wsh_pipe/ila_wsh_pipe.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/l2p_fifo64/l2p_fifo64.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/mig_7series_0/mig_7series_0.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/pcie_7x_0/pcie_7x_0.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.xci"
#    "/home/hirose/work/KC705/RD53A_180726/Yarr-fw/ip-cores/kintex7/tx_fifo/tx_fifo.xci"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_yarr_RD53A_kc705_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project yarr ./yarr -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects yarr]
set_property "board_part" "xilinx.com:kc705:part0:1.3" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../constrs_kc705_timing.xdc"]"\
 "[file normalize "$origin_dir/../constrs_kc705_ddr3.xdc"]"\
 "[file normalize "$origin_dir/../constrs_kc705.xdc"]"\
 "[file normalize "$origin_dir/../constrs_kc705_ila.xdc"]"\
 "[file normalize "$origin_dir/../constrs_kc705_dual_ohio.xdc"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_disp.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut_base.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_lut.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_bram.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_rtl.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/xapp1017/delay_controller_wrap.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/cdr_serdes.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/xapp1017/serdes_1_to_468_idelay_ddr.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_top.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/gn4124_core_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/gearbox32to66.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/descrambler.v"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/aurora_rx_lane.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/data_alignment.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/tx-core/serial_port.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/dma_controller_wb_slave.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/rr_arbiter.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/wbexp_core_pkg.vhd"]"\
 "[file normalize "$origin_dir/board_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/l2p_fifo.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/synchronizer.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/decode_8b10b/decode_8b10b_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/common_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/generic_async_fifo_wrapper.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/tx-core/tx_channel.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/tx-core/trigger_unit.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/p2l_dma_master.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/aurora_rx_channel.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/ddr3k7-core/ddr3_read_core.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/i2c-master/i2c_master_bit_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/dma_controller.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/trigger-logic/delayer.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/ddr3k7-core/ddr3_write_core.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/fei4_rx_channel.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/i2c-master/i2c_master_byte_ctrl.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/i2c-master/i2c_master_registers.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/wbmaster32.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/trigger-logic/eudet_tlu.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/l2p_dma_master.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/l2p_arbiter.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/p2l_decoder.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/trigger-logic/edge_detector.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/simple_counter.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/wb_spi.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/wb_addr_decoder.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/trigger-logic/wb_trigger_logic.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/wbexp-core/wbexp_core.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/i2c-master/i2c_master_wb_top.vhd"]"\
 "[file normalize "$origin_dir/../../xpressk7/app_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/ddr3k7-core/ddr3_ctrl_wb.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/wb_rx_core.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/common/k_dual_bram.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/tx-core/wb_tx_core.vhd"]"\
 "[file normalize "$origin_dir/../../../rtl/kintex7/rx-core/wb_rx_bridge.vhd"]"\
 "[file normalize "$origin_dir/../../xpressk7/app.vhd"]"\
 "[file normalize "$origin_dir/../bram_yarr_kc705_dual_ohio.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "kc705/constrs_kc705_timing.xdc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_global_include" "1" $file_obj

set file "kc705/constrs_kc705_ddr3.xdc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_global_include" "1" $file_obj

set file "kc705/constrs_kc705.xdc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_global_include" "1" $file_obj

set file "kc705/constrs_kc705_ila.xdc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_global_include" "1" $file_obj

set file "kc705/constrs_kc705_dual_ohio.xdc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_disp.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_lut_base.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_lut.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_bram.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_rtl.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "xapp1017/delay_controller_wrap.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/cdr_serdes.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "xapp1017/serdes_1_to_468_idelay_ddr.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_top.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/gn4124_core_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/gearbox32to66.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/descrambler.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj

set file "rx-core/aurora_rx_lane.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/data_alignment.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "tx-core/serial_port.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/dma_controller_wb_slave.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/rr_arbiter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/wbexp_core_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "bram_rd53a_octa_ohio/board_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/l2p_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/synchronizer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "decode_8b10b/decode_8b10b_wrapper.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/common_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/generic_async_fifo_wrapper.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "tx-core/tx_channel.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "tx-core/trigger_unit.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/p2l_dma_master.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/aurora_rx_channel.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "ddr3k7-core/ddr3_read_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "i2c-master/i2c_master_bit_ctrl.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/dma_controller.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "trigger-logic/delayer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "ddr3k7-core/ddr3_write_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/fei4_rx_channel.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "i2c-master/i2c_master_byte_ctrl.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "i2c-master/i2c_master_registers.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/wbmaster32.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "trigger-logic/eudet_tlu.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/l2p_dma_master.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/l2p_arbiter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/p2l_decoder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "trigger-logic/edge_detector.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/simple_counter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/wb_spi.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/wb_addr_decoder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "trigger-logic/wb_trigger_logic.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "wbexp-core/wbexp_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "i2c-master/i2c_master_wb_top.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "xpressk7/app_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "ddr3k7-core/ddr3_ctrl_wb.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/wb_rx_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "common/k_dual_bram.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "tx-core/wb_tx_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "rx-core/wb_rx_bridge.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "xpressk7/app.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj

set file "kc705/bram_yarr_kc705_dual_ohio.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "is_global_include" "1" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top_level" $obj

# Set IP repository paths
#set obj [get_filesets axis_data_fifo_0]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/axis_data_fifo_0/axis_data_fifo_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "axis_data_fifo_0/axis_data_fifo_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets axis_data_fifo_1]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/axis_data_fifo_1/axis_data_fifo_1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "axis_data_fifo_1/axis_data_fifo_1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets clk_gen]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/clk_gen/clk_gen.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_gen/clk_gen.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_256x16]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_256x16/fifo_256x16.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_256x16/fifo_256x16.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_29x32]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_29x32/fifo_29x32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_29x32/fifo_29x32.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_32x512]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_32x512/fifo_32x512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_32x512/fifo_32x512.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_605x32]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_605x32/fifo_605x32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_605x32/fifo_605x32.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_64x512]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_64x512/fifo_64x512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_64x512/fifo_64x512.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_8x32]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_8x32/fifo_8x32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_8x32/fifo_8x32.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets fifo_96x512]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/fifo_96x512_1/fifo_96x512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_96x512_1/fifo_96x512.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets ila_axis]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/ila_axis/ila_axis.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ila_axis/ila_axis.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets ila_ddr]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/ila_ddr/ila_ddr.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ila_ddr/ila_ddr.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets ila_rx_dma_wb]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/ila_rx_dma_wb/ila_rx_dma_wb.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ila_rx_dma_wb/ila_rx_dma_wb.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets ila_wsh_pipe]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/ila_wsh_pipe/ila_wsh_pipe.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ila_wsh_pipe/ila_wsh_pipe.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets l2p_fifo64]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/l2p_fifo64/l2p_fifo64.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "l2p_fifo64/l2p_fifo64.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets mig_7series_0]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/mig_7series_0/mig_7series_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

## Set 'sources_1' fileset file properties for remote files
## None
#
## Set 'sources_1' fileset file properties for local files
#set file "mig_7series_0/mig_7series_0.xci"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets pcie_7x_0]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/pcie_7x_0/pcie_7x_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "pcie_7x_0/pcie_7x_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets rx_bridge_ctrl_fifo]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "rx_bridge_ctrl_fifo/rx_bridge_ctrl_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets rx_bridge_fifo]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/rx_bridge_fifo/rx_bridge_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "rx_bridge_fifo/rx_bridge_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets rx_channel_fifo]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/rx_channel_fifo/rx_channel_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "rx_channel_fifo/rx_channel_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


## Set IP repository paths
#set obj [get_filesets tx_fifo]
#set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../ip-cores"]" $obj
#
## Rebuild user ip_repo's index before adding any source files
#update_ip_catalog -rebuild
#
# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../ip-cores/kintex7/tx_fifo/tx_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "tx_fifo/tx_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "is_global_include" "1" $file_obj


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constrs_kc705_timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constrs_kc705_timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constrs_kc705_ddr3.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constrs_kc705_ddr3.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constrs_kc705.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constrs_kc705.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constrs_kc705_ila.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constrs_kc705_ila.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constrs_kc705_dual_ohio.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constrs_kc705_dual_ohio.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "top_level" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7k325tffg900-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7k325tffg900-2" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:yarr"

# added by minoru
# Need to update IPs
puts "INFO: Updating IPs for KC705"
upgrade_ip [get_ips axis_data_fifo_0]
upgrade_ip [get_ips axis_data_fifo_1]
upgrade_ip [get_ips clk_gen]
upgrade_ip [get_ips fifo_256x16]
upgrade_ip [get_ips fifo_29x32]
upgrade_ip [get_ips fifo_32x512]
upgrade_ip [get_ips fifo_605x32]
upgrade_ip [get_ips fifo_64x512]
upgrade_ip [get_ips fifo_8x32]
upgrade_ip [get_ips fifo_96x512]
upgrade_ip [get_ips ila_axis]
upgrade_ip [get_ips ila_ddr]
upgrade_ip [get_ips ila_rx_dma_wb]
upgrade_ip [get_ips ila_wsh_pipe]
upgrade_ip [get_ips l2p_fifo64]
upgrade_ip [get_ips pcie_7x_0]
upgrade_ip [get_ips rx_bridge_ctrl_fifo]
upgrade_ip [get_ips rx_bridge_fifo]
upgrade_ip [get_ips rx_channel_fifo]
upgrade_ip [get_ips tx_fifo]

puts "INFO: Finished making a project for KC705"

#Synthesize
reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1
set result [get_property STATUS [get_runs synth_1]]
set keyword [lindex [split $result  ] end]
if { $keyword != "Complete!" } {
exit 1
}

puts "INFO: Synthesize done!!"

#Implementation
reset_run impl_1
launch_runs impl_1 -jobs 4
wait_on_run impl_1
set result [get_property STATUS [get_runs impl_1]]
set keyword [lindex [split $result  ] end]
if { $keyword != "Complete!" } {
exit 1
}

puts "INFO: Implementation done!!"

open_run impl_1
write_bitstream -force $origin_dir/test.bit
write_cfgmem -force -format mcs -size 128 -interface BPIx16 -loadbit "up 0x00000000 $origin_dir/test.bit" -file $origin_dir/test.mcs

puts "INFO: Made test.bit and test.mcs files."

exit
